In [1]:
import pandas as pd, numpy as np

In [3]:
data = np.arange(0, 16).reshape(4, 4)

In [8]:
df = pd.DataFrame(data, columns = ["c1", "c2", "c3", "c4"], index = list("abcd"))
df

   c1  c2  c3  c4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [16]:
df["c5"] = np.nan
df.loc["e"] = np.nan
df.loc["e"].c2 = 120
df["c4"]["c"]= np.nan
df["c5"]["d"] = 80
df

     c1     c2    c3    c4    c5
a   0.0    1.0   2.0   3.0   NaN
b   4.0    5.0   6.0   7.0   NaN
c   8.0    9.0  10.0   NaN   NaN
d  12.0   13.0  14.0  15.0  80.0
e   NaN  120.0   NaN   NaN   NaN

In [18]:
df.count().sum()

17

In [22]:
df.notnull().sum().sum()

17

In [24]:
df.isnull().sum().sum()

8

In [26]:
df.shape

(5, 5)

In [28]:
df.c4.dropna()

a     3.0
b     7.0
d    15.0
Name: c4, dtype: float64

In [29]:
df

     c1     c2    c3    c4    c5
a   0.0    1.0   2.0   3.0   NaN
b   4.0    5.0   6.0   7.0   NaN
c   8.0    9.0  10.0   NaN   NaN
d  12.0   13.0  14.0  15.0  80.0
e   NaN  120.0   NaN   NaN   NaN

In [31]:
df.dropna(axis = 0)

     c1    c2    c3    c4    c5
d  12.0  13.0  14.0  15.0  80.0

In [42]:
df.dropna(thresh = 5, axis = 0)

     c1    c2    c3    c4    c5
d  12.0  13.0  14.0  15.0  80.0

In [44]:
df.fillna(df.mean())

     c1     c2    c3         c4    c5
a   0.0    1.0   2.0   3.000000  80.0
b   4.0    5.0   6.0   7.000000  80.0
c   8.0    9.0  10.0   8.333333  80.0
d  12.0   13.0  14.0  15.000000  80.0
e   6.0  120.0   8.0   8.333333  80.0