In [1]:
import pandas as pd, numpy as np

In [2]:
np.random.seed(12)

data = [np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10),]

df = pd.DataFrame({"A": data[0], "B": data[1], "C": data[2], "D": data[3]})
df

    A   B   C   D
0  12  14  26  21
1  28  26  36   7
2   7  35  37  46
3   3  12  36  10
4   4  11  34  46
5   4   1  31  31
6  13  41  33  49
7  49  13  19  33
8  23  14  23  47
9   6  19  17  28

In [10]:
df["A"]
df.A
df[["A", "C"]][:3]

    A   C
0  12  26
1  28  36
2   7  37

In [13]:
np.random.seed(101)
df["E"] = np.random.randint(1, 50, 10)

In [14]:
df

    A   B   C   D   E
0  12  14  26  21  32
1  28  26  36   7  12
2   7  35  37  46  18
3   3  12  36  10   7
4   4  11  34  46  24
5   4   1  31  31  12
6  13  41  33  49  48
7  49  13  19  33  10
8  23  14  23  47  14
9   6  19  17  28  41

In [17]:
df.loc[0]
df.loc[:3]

    A   B   C   D   E
0  12  14  26  21  32
1  28  26  36   7  12
2   7  35  37  46  18
3   3  12  36  10   7

In [19]:
df[["B", "C"]].loc[2:3]

    B   C
2  35  37
3  12  36

In [20]:
df[["B", "C"]][2:4]

    B   C
2  35  37
3  12  36

In [23]:
df.iloc[2:4][["B", "C"]]
df.iloc[2:4, 1:3]

    B   C
2  35  37
3  12  36

In [30]:
df["A"][0] = 100
df.loc[0] = 200, 28, 52, 42, 80
df.loc[10] = 20, 30, 40, 50, 60
df

      A   B   C   D   E
0   200  28  52  42  80
1    28  26  36   7  12
2     7  35  37  46  18
3     3  12  36  10   7
4     4  11  34  46  24
5     4   1  31  31  12
6    13  41  33  49  48
7    49  13  19  33  10
8    23  14  23  47  14
9     6  19  17  28  41
10   20  30  40  50  60

In [31]:
df[["B", "C", "D"]].loc[8]

B    14
C    23
D    47
Name: 8, dtype: int64

In [33]:
df.loc[8][1:4]

B    14
C    23
D    47
Name: 8, dtype: int64

In [37]:
df[["B", "C", "D"]][8:9]

    B   C   D
8  14  23  47

In [39]:
df.iloc[8:9, 1:4]

    B   C   D
8  14  23  47