In [1]:
import pandas as pd

In [3]:
food = {"Dish": ["Curry", "Noodles", "Pasta", "Salad", "Pizza"],
        "GER": [10, 5, 4.5, 2.5, 9],
        "USA": [11, 5, 7, 3, 11],
        "UK": [12, 6, 4, 2.5, 8]}

In [4]:
df_food = pd.DataFrame(food)
df_food

      Dish   GER  USA    UK
0    Curry  10.0   11  12.0
1  Noodles   5.0    5   6.0
2    Pasta   4.5    7   4.0
3    Salad   2.5    3   2.5
4    Pizza   9.0   11   8.0

In [7]:
df_food.shape

(5, 4)

In [15]:
df = pd.melt(df_food, id_vars = "Dish", var_name = "Country", value_name = "Price")

In [23]:
pt = df.pivot_table(index = "Country", values = "Price", columns = "Dish", aggfunc = sum)
pt.loc["USA"]

Dish
Curry      11.0
Noodles     5.0
Pasta       7.0
Pizza      11.0
Salad       3.0
Name: USA, dtype: float64

In [28]:
dish = df.set_index("Country")
dish.shape
d = dish.groupby("Country")
d

In [34]:
d.get_group("USA")

            Dish  Price
Country
USA        Curry   11.0
USA      Noodles    5.0
USA        Pasta    7.0
USA        Salad    3.0
USA        Pizza   11.0

In [35]:
for i in d:
    print(i)

('GER',             Dish  Price
Country
GER        Curry   10.0
GER      Noodles    5.0
GER        Pasta    4.5
GER        Salad    2.5
GER        Pizza    9.0)
('UK',             Dish  Price
Country
UK         Curry   12.0
UK       Noodles    6.0
UK         Pasta    4.0
UK         Salad    2.5
UK         Pizza    8.0)
('USA',             Dish  Price
Country
USA        Curry   11.0
USA      Noodles    5.0
USA        Pasta    7.0
USA        Salad    3.0
USA        Pizza   11.0)

In [37]:
gen = iter(d)
gen

In [40]:
next(gen)

('USA',
             Dish  Price
 Country
 USA        Curry   11.0
 USA      Noodles    5.0
 USA        Pasta    7.0
 USA        Salad    3.0
 USA        Pizza   11.0)

In [44]:
d.min()

          Dish  Price
Country
GER      Curry    2.5
UK       Curry    2.5
USA      Curry    3.0

In [46]:
d.get_group("USA").agg(["max", "std", "mean"])

       Dish      Price
max   Salad  11.000000
std     NaN   3.577709
mean    NaN   7.400000

In [47]:
d.agg(["max", "min", "std", "mean"])

        Price
          max  min       std mean
Country
GER      10.0  2.5  3.174114  6.2
UK       12.0  2.5  3.708099  6.5
USA      11.0  3.0  3.577709  7.4