In [1]:
import pandas as pd

In [6]:
data1 = {"runaways": ["alex", "nico", "chase"], "brain_power": [10, 8, 7]}
df1 = pd.DataFrame(data1)

data2 = {"runaways": ["alex", "nico", "chase"], "power_level": [20, 5, 12]}
df2 = pd.DataFrame(data2)

In [7]:
df1

  runaways  brain_power
0     alex           10
1     nico            8
2    chase            7

In [23]:
pd.merge(df1, df2, on = "runaways", how = "outer", indicator = True)

   runaways brain_power power_level      _merge
0      alex          10          20        both
1      nico           8           5        both
2     chase           7          12        both
3      gert           3         NaN   left_only
4  karolina         NaN          26  right_only

In [16]:
df1.loc[3] = "gert"
df1["brain_power"].loc[3] = 3
df1

df2.loc[3] = "karolina"
df2["power_level"].loc[3] = 26
df2

   runaways power_level
0      alex          20
1      nico           5
2     chase          12
3  karolina          26

In [26]:
df1["health_bar"] = 99, 100, 76, 54
df2["health_bar"] = 99, 100, 76, 2000
df2

   runaways power_level  health_bar
0      alex          20          99
1      nico           5         100
2     chase          12          76
3  karolina          26        2000

In [27]:
pd.merge(df1, df2, on = ["runaways", "health_bar"], how = "outer")

   runaways brain_power  health_bar power_level
0      alex          10          99          20
1      nico           8         100           5
2     chase           7          76          12
3      gert           3          54         NaN
4  karolina         NaN        2000          26