In [1]:
import pandas as pd, numpy as np

In [6]:
df = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/Sales.csv", index_col = 0)
df

    Manager  Price  Product  Quantity   Staff
0   Saminda    800   Laptop         2    Mike
1   Saminda    750   iphone         3  Dashna
2   Rachael    500   iphone         2    Omar
3   Rachael    250   Laptop         4  Callum
4   Saminda    450   Tablet         1    Mike
5   Saminda    299   Tablet         1    Mike
6   Saminda    299   iphone         2  Dashna
7   Rachael    300  Desktop         1    Omar
8   Rachael    250  Desktop         2    Omar
9   Rachael    230   Laptop         1  Callum
10  Saminda    325   Laptop         5  Dashna
11  Rachael    470   iphone         2  Callum

In [7]:
data = {"Staff": ["Mike", "Dashna", "Omar", "Callum", "Mike", "Mike", "Dashna", "Omar",
                  "Omar","Callum", "Dashna", "Callum"],
        
        "Manager": ["Saminda", "Saminda", "Rachael", "Rachael","Saminda", "Saminda",
                    "Saminda", "Rachael", "Rachael", "Rachael", "Saminda", "Rachael"],
         
        "Product": ["Laptop", "iphone", "iphone", "Laptop", "Tablet", "Tablet", "iphone", "Desktop", 
                    "Desktop","Laptop", "Laptop", "iphone"], 
         
        "Quantity": [2, 3, 2, 4, 1, 1, 2, 1, 2, 1, 5, 2],
        
        "Price": [800, 750, 500, 250, 450, 299, 299, 300, 250, 230, 325, 470]} 
    
df = pd.DataFrame(data)

In [8]:
df.head()

    Staff  Manager Product  Quantity  Price
0    Mike  Saminda  Laptop         2    800
1  Dashna  Saminda  iphone         3    750
2    Omar  Rachael  iphone         2    500
3  Callum  Rachael  Laptop         4    250
4    Mike  Saminda  Tablet         1    450

In [11]:
df.pivot_table(index = "Staff", aggfunc = sum)

        Price  Quantity
Staff
Callum    950         7
Dashna   1374        10
Mike     1549         4
Omar     1050         5

In [13]:
df.pivot_table(index = "Product", values = "Price", aggfunc = sum)

         Price
Product
Desktop    550
Laptop    1605
Tablet     749
iphone    2019

In [16]:
df.pivot_table(index = ["Manager", "Staff"], aggfunc = sum).loc["Rachael"]

        Price  Quantity
Staff
Callum    950         7
Omar     1050         5

In [22]:
df.pivot_table(index = ["Manager", "Staff"], values = "Price", 
               aggfunc = [np.sum, min, len, np.var, np.std])

                 sum   min   len           var         std
               Price Price Price         Price       Price
Manager Staff
Rachael Callum   950   230     3  17733.333333  133.166562
        Omar    1050   250     3  17500.000000  132.287566
Saminda Dashna  1374   299     3  64117.000000  253.213349
        Mike    1549   299     3  66050.333333  257.002594

In [28]:
table1 = df.pivot_table(index = ["Manager", "Staff"], values = ["Price", "Quantity"], columns = "Product",
               aggfunc = np.sum, fill_value = 0, margins = True, margins_name = "Total")

In [32]:
table1.query('Manager == ["Saminda"]').T

Manager          Saminda
Staff             Dashna  Mike
         Product
Price    Desktop       0     0
         Laptop      325   800
         Tablet        0   749
         iphone     1049     0
         Total      1374  1549
Quantity Desktop       0     0
         Laptop        5     2
         Tablet        0     2
         iphone        5     0
         Total        10     4