In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/FRUITS.csv", index_col = 0)
df

   APPLE Country  KIWI  MELON  ORANGE  Total  Year
0     20      UK    10      4      30    104  2014
1     40     USA    22     70      50    144  2015
2     32     GER    14     11      48     57  2016
3     12     FRN    11      8      16     93  2017

In [5]:
data = {
    "Country": ["UK", "USA", "GER", "FRN"], 
    "APPLE": [20, 40, 32, 12],
    "ORANGE": [30, 50, 48, 16], 
    "KIWI": [10, 22, 14, 11], 
    "MELON": [4, 70, 11, 8],
    "Year": [2014, 2015, 2016, 2017]}

data["Total"] = [sum(data["APPLE"]), sum(data["ORANGE"]), sum(data["KIWI"]) ,sum(data["MELON"])] 

data
df = pd.DataFrame(data)
df

  Country  APPLE  ORANGE  KIWI  MELON  Year  Total
0      UK     20      30    10      4  2014    104
1     USA     40      50    22     70  2015    144
2     GER     32      48    14     11  2016     57
3     FRN     12      16    11      8  2017     93

In [9]:
df.shape
df.T.shape
df.T
df

  Country  APPLE  ORANGE  KIWI  MELON  Year  Total
0      UK     20      30    10      4  2014    104
1     USA     40      50    22     70  2015    144
2     GER     32      48    14     11  2016     57
3     FRN     12      16    11      8  2017     93

In [25]:
df_set = df[["Country", "Total", "Year", "APPLE"]].set_index(keys = ["Country", "Total", "Year"])
df_set.reset_index(level = [1,2], drop = True).sort_values(by = "APPLE", ascending = False)

         APPLE
Country
USA         40
GER         32
UK          20
FRN         12

In [28]:
df_set.sort_values(by = "APPLE", ascending = False)

                    APPLE
Country Total Year
USA     144   2015     40
GER     57    2016     32
UK      104   2014     20
FRN     93    2017     12